# Site
name: 'Jailand Games'
description: 'Jailand Games is a party of tabletop contrarians. We share our homebrew content here.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'jailand'
email: 'jailandgames@gmail.com'
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
    ali-bobby:
      name:           Ali Bobby
      site:
      avatar:         ../assets/images/authors/ali-bobby.png
      bio:            "I am Ali Bobby, owner of Blood4Gold, the Gigaverse's premier marketplace for part-time adventurers and mercenary gig-work"
      email:          jailandgames@gmail.com

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]